---
- hosts: localhost
  connection: local
  become: yes
  pre_tasks:
    - name: Install libselinux-python
      yum: name=libselinux-python state=present

    - name: Permissive selinux
      selinux: policy=targeted state=permissive

  roles: 
    - role: repositries
    - role: apache
      apache_vhosts_ssl:
        - {servername: "local.example.com", documentroot: "/var/www/html/example/public"}
        # - {servername: "local.egapool.com", documentroot: "/var/www/html/egapool/public"}
        # - {servername: "local.hogehoge.com", documentroot: "/var/www/html/hogehoge/public"}
    - role: git
    - { role: "phpenv", php_versin: "5.6.19"}
