---
- hosts: localhost
  connection: local
  become: yes
  vars_files:
    - group_vars/localhost/main.yml

  pre_tasks:
    - name: Install libselinux-python
      yum: name=libselinux-python state=present

    - name: Permissive selinux
      selinux: policy=targeted state=permissive

  roles: 
    - { role: repositries }
    - { role: geerlingguy.apache, apache_vhosts_version: "2.4" }