---
- name: secure_pathに/usr/local/binを追加
  lineinfile: dest=/etc/sudoers state=present regexp='^Defaults    secure_path' line='Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'

- name: phpenvのインストール
  shell: curl -L https://raw.github.com/CHH/phpenv/master/bin/phpenv-install.sh | bash
  sudo: no

- name: bashファイルの追記
  lineinfile:
    dest: "~/.bashrc"
    line: "export PATH=$HOME/.phpenv/bin:$PATH"
  sudo: no

- lineinfile:
    dest: "~/.bashrc"
    line: eval "$(phpenv init -)"
  sudo: no

- name: .bashrcを再読み込み
  shell: source ~/.bashrc
  sudo: no

- name: pluginsディレクトリを作成
  file: path=~/.phpenv/plugins state=directory
  sudo: no

- name: php-buildをプラグインとしてインストール
  command: git clone git://github.com/php-build/php-build.git chdir=~/.phpenv/plugins
  sudo: no

- name: php依存パッケージをインストール
  yum:
    name: "{{ item }}"
    state: installed
  with_items: 
   - bison 
   - libxml2 
   - libxml2-devel 
   - libxslt-devel 
   - libtidy-devel 
   - readline-devel 
   - libpng 
   - libpng-devel 
   - libjpeg 
   - libjpeg-devel

- name: re2cはrpmforgeから
  yum:
    name: re2c
    state: installed
    enablerepo: "rpmforge"

- name: libmcryptはepelから
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: "epel"
  with_items: 
   - libmcrypt
   - libmcrypt-devel

- command: printenv
  sudo: no

- name: php({{ php_version }})をインストールール
  shell: phpenv install {{ php_version }}
  sudo: no

# shインストール
# bashrc書き込み
# bisonインストール sudo yum install -y bison

# re2c インストール sudo yum -y install --enablerepo=rpmforge re2c

# sudo yum install -y libxml2.x86_64 libxml2-devel.x86_64
# yum install -y libjpeg libjpeg-devel 
# yum install -y libpng libpng-devel
# sudo yum -y install --enablerepo=epel libmcrypt-devel libmcrypt
# sudo yum install -y readline-devel
# sudo yum install -y libtidy-devel
# sudo yum install -y libxslt-devel



# yum install -y bison libxml2 libxml2-devel libxslt-devel libtidy-devel readline-devel libpng libpng-devel libjpeg libjpeg-devel 


# yum install -y --enablerepo=epel php56-php-cli php56-php-fpm php56-php-pdo php56-php-mbstring php56-php-mysqlnd php56-php-mcrypt php56-php-gd php56-php-opcache php56-php-devel


# yum -y install --enablerepo=epel libmcrypt-devel libmcrypt
# yum install -y --enablerepo=remi-php56 php-cli php-fpm php-pdo php-mysqlnd php-mbstring php-gd php-mcrypt php-opcache php-devel